/* cSpell:disable*/ /*eslint-disable*/

let feedText = '';
feedText += '<?xml version="1.0" encoding="UTF-8"?>';
feedText += '<feed xmlns:yt="http://www.youtube.com/xml/schemas/2015" xmlns:media="http://search.yahoo.com/mrss/" xmlns="http://www.w3.org/2005/Atom">';
feedText += ' <link rel="self" href="http://www.youtube.com/feeds/videos.xml?channel_id=UCwIigJTGRHqgUdWO8Fx9Tdg"/>';
feedText += ' <id>yt:channel:UCwIigJTGRHqgUdWO8Fx9Tdg</id>';
feedText += ' <yt:channelId>UCwIigJTGRHqgUdWO8Fx9Tdg</yt:channelId>';
feedText += ' <title>Alain Bernard</title>';
feedText += ' <link rel="alternate" href="https://www.youtube.com/channel/UCwIigJTGRHqgUdWO8Fx9Tdg"/>';
feedText += ' <author>';
feedText += '  <name>Alain Bernard</name>';
feedText += '  <uri>https://www.youtube.com/channel/UCwIigJTGRHqgUdWO8Fx9Tdg</uri>';
feedText += '</author>';
feedText += ' <published>2007-11-20T16:06:02+00:00</published>';
feedText += ' <entry>';
feedText += '  <id>yt:video:aCTWoUEqt0g</id>';
feedText += '  <yt:videoId>aCTWoUEqt0g</yt:videoId>';
feedText += '  <yt:channelId>UCwIigJTGRHqgUdWO8Fx9Tdg</yt:channelId>';
feedText += '  <title>Le système solaire 2 : La révolution de la Terre</title>';
feedText += '  <link rel="alternate" href="https://www.youtube.com/watch?v=aCTWoUEqt0g"/>';
feedText += '  <author>';
feedText += '   <name>Alain Bernard</name>';
feedText += '   <uri>https://www.youtube.com/channel/UCwIigJTGRHqgUdWO8Fx9Tdg</uri>';
feedText += '  </author>';
feedText += '  <published>2018-04-15T16:32:53+00:00</published>';
feedText += '  <updated>2018-06-07T21:13:55+00:00</updated>';
feedText += '  <media:group>';
feedText += '   <media:title>Le système solaire 2 : La révolution de la Terre</media:title>';
feedText += '   <media:content url="https://www.youtube.com/v/aCTWoUEqt0g?version=3" type="application/x-shockwave-flash" width="640" height="390"/>';
feedText += '   <media:thumbnail url="https://i2.ytimg.com/vi/aCTWoUEqt0g/hqdefault.jpg" width="480" height="360"/>';
feedText += '   <media:description>Deuxième vidéo d une série sur le système solaire consacrée à la révolution  de la Terre autour du Soleil.';
feedText += 'Comment mesure-t-on la durée d une journée ?';
feedText += 'La révolution de la Terre détermine les saisons et les variations de la durée d ensoleillement dans une journée.';
feedText += 'Dans la dernière partie, où je visualise le mouvement apparent du Soleil sur une année, j ai placé pour indicateurs qui donnent la date et la latitude.</media:description>';
feedText += '   <media:community>';
feedText += '    <media:starRating count="259" average="4.97" min="1" max="5"/>';
feedText += '    <media:statistics views="4714"/>';
feedText += '   </media:community>';
feedText += '  </media:group>';
feedText += ' </entry>';
feedText += '</feed>';
//return feedText;
